/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package wordbuilder;

import database.DatabaseOperations;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Mohit
 */
public class ForgotPassword extends javax.swing.JFrame {

    /**
     * Creates new form ForgotPassword
     */
    public ForgotPassword() {
        initComponents();
         this.setLocation(scrSize.width - (scrSize.width)/2 - (this.getWidth())/2 ,scrSize.height -(scrSize.height*1)/2 - (this.getHeight())/2  );
    }

       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        enter = new javax.swing.JButton();
        secques = new javax.swing.JLabel();
        secans = new javax.swing.JLabel();
        answer = new javax.swing.JTextField();
        check = new javax.swing.JButton();
        questionlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Forgot Password");
        setResizable(false);

        jLabel1.setText("username");

        username.setToolTipText("min 2 chars max 15");
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        enter.setText("Enter");
        enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterActionPerformed(evt);
            }
        });

        secques.setText("Security Question");

        secans.setText("Security Answer");

        answer.setToolTipText("min 2 chars 20 max");

        check.setText("Check");
        check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkActionPerformed(evt);
            }
        });

        questionlabel.setText("Question");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(check)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(secans)
                            .addComponent(secques)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(questionlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(username, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                            .addComponent(answer))))
                .addGap(26, 26, 26)
                .addComponent(enter)
                .addContainerGap(131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enter))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(secques)
                    .addComponent(questionlabel))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(secans)
                    .addComponent(answer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(check)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        secques.setVisible(false);
        secans.setVisible(false);
        answer.setVisible(false);
        check.setVisible(false);
        questionlabel.setVisible(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterActionPerformed
        // TODO add your handling code here:
       //  DatabaseOperations d= new DatabaseOperations();
              ArrayList<String> list=new ArrayList<String>();
              String pass,ques,ans,answ;
        String user=this.username.getText();
        
        boolean cond1=true;
        
        boolean  cond2=false;
        
      if(user.length()>=2 && user.length()<=15)
        { 
          try {
              cond1=true;
               list=DatabaseOperations.recoverPassword(user);
               pass=list.get(0);
               ques=list.get(1);
               ans=list.get(2);
              if(pass.length()>=2 && ques.length()>=2 && ans.length()>=2){
                  
        WordBuilder.forgotpassword.secques.setVisible(true);
        WordBuilder.forgotpassword.answer.setVisible(true);
        WordBuilder.forgotpassword.secans.setVisible(true);
        WordBuilder.forgotpassword.questionlabel.setText(ques);
        WordBuilder.forgotpassword.questionlabel.setVisible(true);
        WordBuilder.forgotpassword.check.setVisible(true);
        WordBuilder.forgotpassword.username.setEditable(false);
        WordBuilder.forgotpassword.enter.setVisible(false);
              }
              
          } catch (SQLException ex) {
              Logger.getLogger(ForgotPassword.class.getName()).log(Level.SEVERE, null, ex);
          } catch (ClassNotFoundException ex) {
              Logger.getLogger(ForgotPassword.class.getName()).log(Level.SEVERE, null, ex);
          }
        }else{
            cond1=false;
            JOptionPane.showMessageDialog(this, "Check Username Character Length", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
      
        
      /*
        jLabel2.setVisible(true);
        answer.setVisible(true);
        jLabel3.setVisible(true);
        questionlabel.setVisible(true);
        * */
    }//GEN-LAST:event_enterActionPerformed

    private void checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkActionPerformed
        // TODO add your handling code here:
          ArrayList<String> list=new ArrayList<String>();
              String pass,ques,ans,answ;
        
     //   DatabaseOperations d=new DatabaseOperations();
                System.out.println("check");
                boolean  cond2=false;
                String user;
                user=WordBuilder.forgotpassword.username.getText();
                try {
                    answ=WordBuilder.forgotpassword.answer.getText();
                     list=DatabaseOperations.recoverPassword(user);
                   pass=list.get(0);
                   ques=list.get(1);
                   ans=list.get(2);
                  
                    if(answ.equals(ans)){
                        cond2=true;
                        JOptionPane.showMessageDialog(this, "Your password is "+pass, "Password", JOptionPane.INFORMATION_MESSAGE);
                         WordBuilder.forgotpassword.setVisible(false);
                WordBuilder.signin.setVisible(true);
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(ForgotPassword.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(ForgotPassword.class.getName()).log(Level.SEVERE, null, ex);
                }
            if(cond2){
               
            }
    }//GEN-LAST:event_checkActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassword().setVisible(true);
            }
        });
    }
    private Dimension scrSize = Toolkit.getDefaultToolkit().getScreenSize();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    static javax.swing.JTextField answer;
    static javax.swing.JButton check;
    public static javax.swing.JButton enter;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel questionlabel;
    static javax.swing.JLabel secans;
    public static javax.swing.JLabel secques;
    public static javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
